# Generated by Django 5.2.6 on 2025-10-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='cofrence_id',
            new_name='conference_id',
        ),
    ]
