# Generated by Django 5.2.6 on 2025-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_rename_cofrence_id_conference_conference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizingcommittee',
            name='committee_role',
            field=models.CharField(choices=[('Chair', 'Chair'), ('Co-Chair', 'Co-Chair'), ('Member', 'Member')], default='Member', max_length=100),
        ),
    ]
